'use client';

import React, { useState } from 'react';
import { useMutation } from '@tanstack/react-query';
import { apiClient } from '@/lib/api-client';
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Card } from '@/components/ui/card';
import { Loader2Icon, SparklesIcon } from 'lucide-react';

interface QuestionExplanationModalProps {
  questionId: string;
  userAnswer?: any;
  isOpen: boolean;
  onClose: () => void;
}

export function QuestionExplanationModal({
  questionId,
  userAnswer,
  isOpen,
  onClose,
}: QuestionExplanationModalProps) {
  const [explanation, setExplanation] = useState<string | null>(null);
  const [sources, setSources] = useState<string[]>([]);
  const [cost, setCost] = useState<number>(0);

  const explainMutation = useMutation({
    mutationFn: async () => {
      const response = await apiClient.post(`/tutor/explain/${questionId}`, {
        userAnswer,
      });
      return response.data;
    },
    onSuccess: (data) => {
      setExplanation(data.message);
      setSources(data.sources || []);
      setCost(data.cost);
    },
  });

  React.useEffect(() => {
    if (isOpen && !explanation) {
      explainMutation.mutate();
    }
  }, [isOpen]);

  const handleClose = () => {
    setExplanation(null);
    setSources([]);
    setCost(0);
    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="max-w-3xl max-h-[80vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <SparklesIcon className="h-5 w-5 text-purple-600" />
            AI Explanation
          </DialogTitle>
          <DialogDescription>
            Detailed explanation powered by AI Tutor
          </DialogDescription>
        </DialogHeader>

        <div className="space-y-4 mt-4">
          {explainMutation.isPending ? (
            <Card className="p-8 flex items-center justify-center">
              <div className="text-center">
                <Loader2Icon className="h-8 w-8 animate-spin text-blue-600 mx-auto mb-3" />
                <p className="text-sm text-muted-foreground">
                  Generating explanation...
                </p>
              </div>
            </Card>
          ) : explainMutation.isError ? (
            <Card className="p-6 bg-red-50 dark:bg-red-950">
              <p className="text-sm text-red-600 dark:text-red-400">
                Failed to generate explanation. Please try again.
              </p>
              <Button
                variant="outline"
                size="sm"
                className="mt-3"
                onClick={() => explainMutation.mutate()}
              >
                Retry
              </Button>
            </Card>
          ) : explanation ? (
            <>
              <Card className="p-6">
                <div className="prose prose-sm max-w-none dark:prose-invert">
                  <div className="whitespace-pre-wrap">{explanation}</div>
                </div>
              </Card>

              {sources.length > 0 && (
                <Card className="p-4 bg-gray-50 dark:bg-gray-800">
                  <p className="text-sm font-medium mb-2">Sources:</p>
                  <div className="flex flex-wrap gap-2">
                    {sources.map((source, idx) => (
                      <Badge key={idx} variant="secondary">
                        📚 {source}
                      </Badge>
                    ))}
                  </div>
                </Card>
              )}

              <div className="flex items-center justify-between text-xs text-muted-foreground">
                <span>Generated by AI Tutor</span>
                <span>Cost: ${cost.toFixed(4)}</span>
              </div>
            </>
          ) : null}
        </div>

        <div className="flex justify-end gap-2 mt-6">
          <Button variant="outline" onClick={handleClose}>
            Close
          </Button>
          <Button onClick={() => window.location.href = '/tutor'}>
            Ask Follow-up
          </Button>
        </div>
      </DialogContent>
    </Dialog>
  );
}
